source 'http://rubygems.org'

gem 'rails'
gem 'rack' # temporarily to hide warning
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'will_paginate'
